---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"

inputs:
- name: resource-web-app

outputs:
- name: built-project

run:
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$PWD/resource-web-app
      go build -v -x
